server:
  port: 9292
  
spring:
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS

management:
  server:
    port: 9001
    address: 127.0.0.1
  metrics:
    export:
       prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        
astra:
  application-token: CHANGE_ME
  database-id: CHANGE_ME
  database-region: CHANGE_ME
  keyspace: quickstart