server:
  port: 9292
  
spring:
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS

management:
  server:
    port: 9001
    address: 127.0.0.1
  metrics:
    export:
       prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        
astra:
  api:
    application-token: change_me
    database-id: change_me
    database-region: change_me
  cql:
    enabled: true
    download-scb: 
      enabled: true
    metrics: 
      enabled: true
    driver-config:
      basic:
        session-keyspace: quickstart
        